mysite/shopapp/urls.py
from django.urls import path, include
from .views import (shop_index,
                    ProductListView,
                    OrderListView,
                    ProductCreateView,
                    OrderCreateView,
                    ProductDetailView,
                    ProductUpdateView,
                    ProductArchiveView,
                    OrderDetailView,
                    OrderUpdateView,
                    OrderDeleteView,
                    OrdersExportView,
                    LatestProductsFeed,
                    UserOrderListView,
                    user_orders_export
                    )
from rest_framework.routers import DefaultRouter
from .views import ProductViewSet, OrderViewSet

routers = DefaultRouter()
routers.register('products', ProductViewSet)
routers.register('orders', OrderViewSet)


app_name = 'shopapp'

urlpatterns = [
    path('', shop_index, name='index'),
    path('api/', include(routers.urls)),
    path('products/', ProductListView.as_view(), name='products_list'),
    path('products/latest/feed', LatestProductsFeed(), name='latest_products_feed'),
    path('products/create/', ProductCreateView.as_view(), name='create_new_product'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('products//<int:pk>archive/', ProductArchiveView.as_view(), name='archive_product'),
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('orders/create/', OrderCreateView.as_view(), name='create_new_order'),
    path('orders/export/', OrdersExportView.as_view(), name='orders_export'),
    path('users/<int:user_id>/orders/', UserOrderListView.as_view(), name='user_orders'),
    path('users/<int:user_id>/orders/export/', user_orders_export, name='user_orders_export'),
]

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/basemodel.html' %}

{% block title %}
    Create a new order
{% endblock %}

{% block body %}
    <h2> Create a new order </h2>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Create </button>
    </form>
    </div>
    <p>
    <a href="{% url "shopapp:orders_list" %}"> Back to see orders list</a>
    </p>
{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends "shopapp/basemodel.html" %}

{% block title %}
    Create-product
{% endblock %}

{% block body %}
    <h2> Create a new product</h2>
    <div>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
        </form>
    </div>
    <p>
    <a href="{% url 'shopapp:products_list' %}" > Back to products list </a>
    </p>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends "shopapp/basemodel.html" %}

{% block title %}
    Delete order {{ object.pk }}
{% endblock %}

{% block body %}
    <h2> Are you sure you want to delete order <em>#{{ object.pk }}</em>?</h2>
    <form method="post">

    {% csrf_token %}
        <p><a href="{% url "shopapp:order_detail" pk=object.pk %}">Back to order <em>#{{ object.pk }}</em></a></p>
        <br>
        {{ form.as_p }}
        <button type="submit">Delete</button>
    </form>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/basemodel.html' %}

{% block title %}
    Order #{{ order.pk }}
{% endblock %}

{% block body %}
    <h1>Details of order #{{ order.pk }}</h1>
    <p>    Made by user:  {{ order.user }}</p>
    <p>    Promocode:  {{ order.promocode }}</p>
    <p>    Delivery_address: {{ order.delivery_address }} </p>
            <p>    Products in order:
                   <ul>
                   {% for product in order.products.all  %}
                       <li> {{ product.name }}, price - {% firstof product.price 'no price set yet'%} $ </li>
                   {% empty %}
                       No products added to order
                   {% endfor %}
                   </ul>
                </p>
    <br>
    <p> <a href="{% url "shopapp:order_list" %}">Back to list of orders</a> </p>
    <p> <a href="{% url "shopapp:order_update" pk=order.pk %}">Update order</a></p>
    <p> <a href="{% url "shopapp:order_delete" pk=order.pk %}">Delete order</a></p>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends "shopapp/basemodel.html" %}

{% block title %}
Orders list
{% endblock %}


{% block body %}
    <h3> Current orders list: </h3>
    <div>
    {% if object_list %}
        <ul>
        {% for order in object_list %}
            <li>
            <p> <a href="{% url "shopapp:order_detail" pk=order.pk %}">Order #{{ order.pk }}</a>  made by user "{{ order.user }}"</p>
            <p>    Delivery_address: {{ order.delivery_address }} </p>
            <p>    Products in order:
                   <ul>
                   {% for product in order.products.all  %}
                       <li> {{ product.name }}, price - {% firstof product.price 'no price set yet'%} $ </li>
                   {% empty %}
                       No products added to order
                   {% endfor %}
                   </ul>
                </p>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <h4> No orders yet </h4>
    {%  endif %}
    </div>

    <p>
    <a href="{% url "shopapp:create_new_order" %}"> To create a new order</a>
    </p>

{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/basemodel.html' %}

{% block title %}
    Update order #{{ object.pk }}
{% endblock %}

{% block body %}
    <h1> Update order #{{ object.pk }}</h1>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Update </button>
    </form>
    </div>
    <p>
    <a href="{% url "shopapp:order_list" %}"> Back to see orders list</a>
    </p>
    <p>
    <a href="{% url "shopapp:order_detail" pk=object.pk %}">Back to order #{{ object.pk }}</a>
    </p>
{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends "admin/change_list.html" %}

{% block object-tools-items %}
    <li>
    <a href="{% url "admin:import_csv" %}" class="addlink">Import CSV</a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_archive.html
{% extends 'shopapp/basemodel.html' %}

{% block title %}
    Archive product}
{% endblock %}

{% block body %}
    <h2> Are you sure you want to archive product <em>#{{ object.name }}</em>?</h2>
    <form method="post">

    {% csrf_token %}
        <p><a href="{% url "shopapp:product_detail" pk=object.pk %}">Back to product <em>#{{ object.name }}</em></a></p>
        <br>
        {{ form.as_p }}
        <button type="submit">Archive</button>
    </form>
{% endblock %}

mysite/shopapp/templates/shopapp/product_detail.html
{% extends 'shopapp/basemodel.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Product' %}: {{object.pk}}
{% endblock %}

{% block body %}
    <h2> {% translate 'Product' %}<em>#{{ object.pk}}</em></h2>
    {% blocktranslate with name=object.name description=object.description price=object.price archived=object.archived %}
        <p>Name: <span style="color: saddlebrown">{{ name }}</span></p>
        <p>Description: <span style="color: saddlebrown">{{ description }}</span></p>
        <p>Price: <span style="color: saddlebrown">{{ price }}</span></p>
        <p>Archived: <span style="color: saddlebrown">{{ archived }}</span></p>
    {% endblocktranslate %}

    <div>
    {% blocktranslate count images_num=object.images.all|length %}
        <p>For product {{ images_num }} image available:</p>
        {% plural %}
        <p>For product {{ images_num }} images available:</p>
    {% endblocktranslate %}
    {% for image in object.images.all %}
        <div>
        <img src="{{ image.image.url }}" alt="{{ ímage.image.name }}">
        </div>
    {% endfor %}
    </div>
    <br>
    <p><a href="{% url "shopapp:products_list" %}"> {% translate 'Back to list of products' %}</a></p>
    <p><a href="{% url "shopapp:update_product" pk=object.pk %}">{% translate 'Update product' %}</a></p>
    <p><a href="{% url "shopapp:archive_product" pk=object.pk %}">{% translate 'Archive product' %}</a></p>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends "shopapp/basemodel.html" %}

{% block title %}
    Create-product
{% endblock %}

{% block body %}
    <h2> Create a new product</h2>
    <div>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
        </form>
    </div>
    <p>
    <a href="{% url 'shopapp:products_list' %}" > Back to products list </a>
    </p>
{% endblock %}

mysite/shopapp/templates/shopapp/product_list.html
{% extends "shopapp/basemodel.html" %}

{% block title %}
Products list
{% endblock %}



{% block body %}
<h2> Products to order:
</h2>
    <div>
        {% if products %}
        <ul>
            {% for product in products %}
            <li>
                <p> Product name: <a href="{% url "shopapp:product_detail" pk=product.pk %}">{{product.name}}</a></p>
                <p> Description: {% firstof product.description 'No description' %} </p>
                <p> Price:
                    {% if product.price == 0 %}
                     No price set yet
                    {% else %}
                    {{product.price}} $
                    {% endif %}
                </p>
                <p> Discount %: {% firstof product.discount 'no discount' %} </p>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        No products yet
        {% endif %}

    </div>
    <br>
    {% if 'shopapp.add_product' in perms %}
        <div>
        <a href="{% url 'shopapp:create_new_product' %}"> Create a new product </a>
        </div>
    {%  endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends "shopapp/basemodel.html" %}

{% block title %}
Products list
{% endblock %}



{% block body %}
<h3> Products to order:
</h3>
    <div>
        {% if products %}
        <ul>
            {% for product in products %}
            <li>
                <p> Product name: {{ product.name }} </p>
                <p> Description: {% firstof product.description 'No description' %} </p>
                <p> Price:
                    {% if product.price == 0 %}
                     No price set yet
                    {% else %}
                    {{product.price}} $
                    {% endif %}
                </p>
                <p> Discount %: {% firstof product.discount 'no discount' %} </p>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        No products yet
        {% endif %}

    </div>
    <div>
    <a href="{% url 'shopapp:create_new_product' %}"> Create a new product </a>
    </div>


{% endblock %}

mysite/shopapp/templates/shopapp/shopapp-index.html
{% extends 'shopapp/basemodel.html'%}

{% block title %}
    Shop Index
{% endblock %}


{% block body %}
    <h2> COSMETICS STORE </h2>
    <div>
    Today is {% now 'd.m.Y' %}
    </div>

    <h4> Welcome to cosmetics store! </h4>
    {%  for link in menu %}
        <div> <a href={% url link.url_name %}> {{ link.title}} </a></div>
    {% endfor %}
{% endblock %}

mysite/shopapp/templates/shopapp/user_orders_list.html
{% extends "shopapp/basemodel.html" %}
{% load cache %}

{% block title %}
Orders list
{% endblock %}


{% block body %}
    <div>
    {% if object_list %}
        <h3> User {{ owner }} made next orders: </h3>
        {%  cache 300 user_orders owner.pk %}
        <ul>
        {% for order in object_list %}
            <li>
            <p> <a href="{% url "shopapp:order_detail" pk=order.pk %}">Order #{{ order.pk }}</a></p>
            <p>    Delivery_address: {{ order.delivery_address }} </p>
            <p>    Products in order:
                   <ul>
                   {% for product in order.products.all  %}
                       <li> {{ product.name }}, price - {% firstof product.price 'no price set yet'%} $ </li>
                   {% empty %}
                       No products added to order
                   {% endfor %}
                   </ul>
                </p>
            </li>
        {% endfor %}
        </ul>
        {%  endcache %}
    {% else %}
        <h3> There is no orders for user {{ owner }} yet</h3>
    {%  endif %}
    </div>

    <p>
    <a href="{% url "shopapp:create_new_order" %}"> To create a new order</a>
    </p>

{% endblock %}