mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from myauth.views import (MyLogoutView, cookies_set, cookies_get,
                          session_set, session_get, RegistrationView,
                          ProfileDetailView, UserListView, ProfileUpdateView,
                          about_me)

app_name = 'myauth'

urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='myauth/login.html',
        redirect_authenticated_user=True),
         name='login'),
    path('logout/',
         MyLogoutView.as_view(),
         name='logout'),
    path('about-me/',
         about_me,
         name='about_me'),
    path('register/',
         RegistrationView.as_view(), name='registration'),
    path('cookies-set/',
         cookies_set,
         name='cookies_set'),
    path('cookies-get/',
         cookies_get,
         name='cookies_get'),
    path('session-set/',
         session_set,
         name='session_set'),
    path('session-get/',
         session_get,
         name='session_get'),
    path('profiles/',
         UserListView.as_view(),
         name='profile_list'),
    path('profiles/<int:pk>/',
         ProfileDetailView.as_view(),
         name='profile_detail'),
    path('profiles/<int:pk>/update/',
         ProfileUpdateView.as_view(),
         name='profile_update')
]

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def get_avatar_file_name(instance: 'Profile', filename) -> str:
    return "profiles/profile_{pk}/{filename}".format(pk=instance.user.pk, filename=filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    bio = models.TextField(blank=True)
    agreement_signed = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=get_avatar_file_name)

mysite/myauth/forms.py
from django import forms
from .models import Profile


class OnlyAvatarForm(forms.Form):
    avatar = forms.ImageField(label='To upload new image')

mysite/myauth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView, TemplateView
from .forms import OnlyAvatarForm
from django.contrib.auth.models import User
from myauth.models import Profile


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('myauth:login')


class RegistrationView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about_me')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password2')
        user = authenticate(request=self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


def cookies_get(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('cookie_value', 'default_value')
    return HttpResponse(f'Cookie value: {value!r}')


def cookies_set(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookies value set!')
    response.set_cookie('cookie_value', 'rabbit', max_age=3600)
    return response


def session_set(request: HttpRequest) -> HttpResponse:
    request.session['session_value'] = "Christmas soon!"
    return HttpResponse('Session value set!')


def session_get(request: HttpRequest) -> HttpResponse:
    value = request.session.get('session_value', 'Value is not set yet!')
    return HttpResponse(f'Session value: {value}')


class ProfileDetailView(DetailView):
    model = Profile


class UserListView(ListView):
    template_name = 'myauth/user_list.html'
    queryset = User.objects.select_related('profile')


class ProfileUpdateView(UserPassesTestMixin, UpdateView):
    model = Profile
    fields = 'avatar', 'bio'

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.is_staff or self.request.user.profile == self.object

    def get_success_url(self):
        return reverse('myauth:profile_detail', kwargs={'pk': self.object.pk})


def about_me(request: HttpRequest):
    if request.method == 'POST' and request.FILES['avatar']:
        form = OnlyAvatarForm(request.POST, request.FILES)
        if form.is_valid():
            profile, created = Profile.objects.get_or_create(user=request.user)
            profile.avatar = form.cleaned_data['avatar']
            profile.save()
    form = OnlyAvatarForm()
    context = {'form': form}
    return render(request, 'myauth/about_me.html', context=context)

mysite/myauth/templates/myauth/about_me.html
{% extends 'myauth/base.html' %}

{% block title %}
    About me
{% endblock %}
{% block body %}
    {% if request.user.username %}
        <h2>Current user:</h2>
        <p> <u>Avatar:</u></p>
        {%  if request.user.profile.avatar  %}
        <div> <img src="{{ request.user.profile.avatar.url }}" alt="{{ request.user.profile.avatar.name }}"></div>
        {% else %}
            <i>No avatar set yet</i>
        {% endif %}
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form.as_p }}
        <p> <u>Username:</u> {{ request.user.username }} </p>
        <p> <u>Email:</u> {{ request.user.email }} </p>
        <p> <u>Biography:</u> {{ request.user.profile.bio }} </p>
        <button type="submit">Save changes</button>
        </form>
    {% else %}
        <h2>Anonymous user</h2>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <h2>Enter username and password to login:</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">LOGIN</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/profile_detail.html
{% extends 'myauth/base.html' %}

{% block title %}
    Profile: {{object.pk}}
{% endblock %}

{% block body %}
    <h2>Profile <em>#{{ object.pk}}</em></h2>
    <table>
    <tr>
        <td>Avatar: </td>
        {% if object.avatar %}
        <td style="color: saddlebrown"> <img src="{{ object.avatar.url }}" alt="{{ object.avatar.name }}"></td>
        {% else %}
            <td><i>No avatar set yet</i></td>
        {% endif %}
    </tr>

    <tr>
        <td>Username: </td>
        <td style="color: saddlebrown">{{ object.user.username }}</td>
    </tr>
    <tr>
    <tr>
        <td>Biography: </td>
        <td style="color: saddlebrown">{{ object.bio }}</td>
    </tr>
    <tr>
        <td>Email: </td>
        <td style="color: saddlebrown">{{ object.user.email }}</td>
    </tr>
    </table>
    <br>
    <p><a href="{% url "myauth:profile_list" %}">Back to list of profiles</a></p>
    {% if request.user.is_staff or request.user.pk == object.user.pk  %}
        <p><a href="{% url "myauth:profile_update" pk=object.pk %}">Update Profile</a></p>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/profile_form.html
{% extends 'shopapp/basemodel.html' %}

{% block title %}
    Update order #{{ object.pk }}
{% endblock %}

{% block body %}
    <h1> Update Profile #{{ object.pk }}</h1>
    <div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Update </button>
    </form>
    </div>
    <p>
    <a href="{% url "myauth:profile_list" %}"> Back to see profiles list</a>
    </p>
    <p>
    <a href="{% url "myauth:profile_detail" pk=object.pk %}">Back to profile #{{ object.pk }}</a>
    </p>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
Registration
{% endblock %}

{% block body %}
    <h1>Registration form</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user_list.html
{% extends "myauth/base.html" %}

{% block title %}
Users list
{% endblock %}


{% block body %}
<h2> Existing users on site: </h2>
    <div>
        {% if object_list %}
        <ul>
            {% for user in object_list %}
            <li>
                <p> Username: <a href="{% url "myauth:profile_detail" pk=user.profile.pk %}">{{user.username}}</a></p>
                <p> Email: {% firstof user.email 'No email' %} </p>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        No users yet
        {% endif %}
    </div>

{% endblock %}