mysite/blogapp/urls.py
from django.urls import path
from .views import ArticleListView, ArticleCreateView

app_name = 'blogapp'

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='article_list'),
    path('articles/create/', ArticleCreateView.as_view(), name='article_create'),
]

mysite/blogapp/models.py
import datetime

from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    bio = models.TextField(blank=True)

    def __str__(self) -> str:
        return f"{self.name!r}"


class Category(models.Model):
    name = models.CharField(max_length=40, null=False)

    def __str__(self) -> str:
        return f"Category {self.name!r}"


class Tag(models.Model):
    name = models.CharField(max_length=20, null=False)

    def __str__(self) -> str:
        return f"{self.name!r}"


class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(blank=False)
    pub_date = models.DateTimeField(blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, related_name='articles')

mysite/blogapp/views.py
from django.views.generic import ListView, CreateView
from .models import Article
from django.urls import reverse_lazy


class ArticleListView(ListView):
    queryset = Article.objects.defer('content').select_related('author').select_related('category').prefetch_related(
        'tags')


class ArticleCreateView(CreateView):
    model = Article
    fields = 'title', 'content', 'pub_date', 'author', 'category', 'tags'
    success_url = reverse_lazy('blogapp:article_list')

mysite/blogapp/templates/blogapp/article_form.html
{% extends "blogapp/base.html" %}

{% block title %}
    Create-article
{% endblock %}

{% block body %}
    <h2> Create a new article</h2>
    <div>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
        </form>
    </div>
    <p>
    <a href="{% url 'blogapp:article_list' %}" > Back to products list </a>
    </p>
{% endblock %}

mysite/blogapp/templates/blogapp/article_list.html
{% extends "blogapp/base.html" %}

{% block title %}
    List of articles
{% endblock %}


{% block body %}
    <h2> List of articles: </h2>
    <div>
    {% if object_list %}
        <ul>
        {% for article in object_list %}
            <li>
            <p> Title: "{{ article.title }}"</p>
            <p> Publication date: {{ article.pub_date|date:"d.m.Y"}} </p>
            <p> Author: {{ article.author.name }} </p>
            <p> Category: {{ article.category.name }} </p>
            <p>    Tags of article:
                   <ul>
                   {% for tag in article.tags.all  %}
                       <li> {{ tag.name }} </li>
                   {% empty %}
                       No tags added to article
                   {% endfor %}
                   </ul>
                </p>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <h4> No articles yet </h4>
    {%  endif %}

    <p>
    <a href="{% url 'blogapp:article_create' %}"> Create a new article </a>
    </p>

    </div>

{% endblock %}

mysite/blogapp/templates/blogapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        * {
            font-family: 'Arial', 'sans-serif'
        }
    </style>

    <title>
        {% block title %}
            Базовый шаблон
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
Это базовый шаблон, сделайте наследование от него!
{% endblock %}

</body>
</html>